### ISSUE TITLE
Create Player Physics

### ISSUE THREAD

**Issue by danyooo** [danyooo/SwordFightingGame#25]
Should have inertia and not be able to completely change direction instantly.
The player should also be able to be knocked back when their sword / they are collided with by a sword( and when they hit a wall)

**Comment by danyooo** [comment]
Movement is complete, need collision now.

**Comment by danyooo** [comment]
https://youtu.be/S9Jd6Ss8tU0
Having trouble with players colliding off of each other // detecting collisions and doing osmething with that collision. Tomorrow when I have time will look at this video (just noting it down)

**Comment by Spaghettimonstar** [comment]
Remove Area2D
and check if collision code works

**Comment by danyooo** [comment]
> Remove Area2D and check if collision code works
This half-worked. The solution was adding two collisionboxes, one for AREA2D, and one for the player. the AREA2D should be slightly larger than the player's collision box.

**Comment by Spaghettimonstar** [comment]
add code comments to the knockback parts
